# Generated by Django 4.1.4 on 2023-01-25 20:41

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bon_commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_document', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('qte', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)])),
            ],
        ),
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('prenom', models.CharField(max_length=20)),
                ('adress', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Comptes',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('prenom', models.CharField(max_length=20)),
                ('adress', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=10)),
                ('solde', models.FloatField(default=0, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='type_produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('typep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_produit', to='Gestion_Stock.type_produit')),
            ],
        ),
        migrations.CreateModel(
            name='facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_document', models.DateTimeField(default=datetime.datetime.now)),
                ('code_document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='code_document1', to='Gestion_Stock.bon_commande')),
                ('facture_avoir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fournisseur_facture', to='Gestion_Stock.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='entree_stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)])),
                ('prix_achat', models.FloatField(default=0, max_length=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('prix_vente', models.FloatField(default=0, max_length=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('contient_produit', models.ManyToManyField(to='Gestion_Stock.bon_commande')),
            ],
        ),
        migrations.AddField(
            model_name='bon_commande',
            name='contient',
            field=models.ManyToManyField(related_name='produit', to='Gestion_Stock.produit'),
        ),
        migrations.CreateModel(
            name='bl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_document', models.DateTimeField(default=datetime.datetime.now)),
                ('bl_avoir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fornisseur_bl', to='Gestion_Stock.fournisseur')),
                ('code_document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='code_document2', to='Gestion_Stock.bon_commande')),
            ],
        ),
    ]
